### ISSUE TITLE
[BUG] Program is not high-DPI aware

### ISSUE THREAD

**Issue by ahiijny** [Tudi20/Universal-THCRAP-Launcher#10]
**Describe the bug**
On a high-DPI display, the text looks fuzzy. Usually this happens if the app is not high-DPI aware.

If I try the usual workaround of `exe > right click > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior. Scaling performed by: Application`, then the program won't open for some reason.

Possibly relevant links:
- https://stackoverflow.com/questions/13228185/how-to-configure-an-app-to-run-correctly-on-a-machine-with-a-high-dpi-setting-e
- https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

**Screenshots**
![fuzzy text inside the application but sharp text in the title bar](https://user-images.githubusercontent.com/5766317/54249575-06134000-4517-11e9-99aa-c907136e6016.png)

**System Info:**
 - OS: Windows 10 version 1803, display 1920x1080 with 125% scaling
 - thcrap launcher: version 2019-01-17

**Comment by lilyremigia** [comment]
@ahiijny Can you test if the new [pre-release](https://github.com/Tudi20/Universal-THCRAP-Launcher/releases/tag/1.0.0-pre1) makes the program high DPI aware?

**Comment by ahiijny** [comment]
Hm, the problem still persists. It still looks blurry on my high-DPI monitor. For comparison:

High-DPI monitor:
![201905241745 - high DPI monitor](https://user-images.githubusercontent.com/5766317/58358215-fe8fe180-7e4b-11e9-8f01-612f3a81adf1.PNG)

Standard-DPI monitor:
![201905241745 - standard DPI monitor](https://user-images.githubusercontent.com/5766317/58358227-09e30d00-7e4c-11e9-85ac-6c90057148b9.PNG)
