### ISSUE TITLE
[BUG] Can't open the program.

### ISSUE THREAD

**Issue by Yanstory** [Tudi20/Universal-THCRAP-Launcher#12]
Can't open the program with no window pop.
I use Simplified Chinese system, is that the source?

**Comment by lilyremigia** [comment]
Can you check if in English, it works?

**Comment by Yanstory** [comment]
I think it doesn't. I use Locale Emulator and it's still not working.

**Comment by lilyremigia** [comment]
You can send the log, maybe I can figure it out from that.

**Comment by Yanstory** [comment]
There's no log file related with UTL near the exe, but I found an error by using dnspy. Here's the screenshot.
![image](https://user-images.githubusercontent.com/5153875/55415627-efa15700-559f-11e9-86d9-902fd72e3152.png)

**Comment by lilyremigia** [comment]
Do you have any external programs that resizes program, or something similar to that?

**Comment by Yanstory** [comment]
I used one called ``AutoSizer`` but only used for FDF2, I'm also running Wallpaper Engine and ShareX but they don't affect any program.

**Comment by lilyremigia** [comment]
@Tudi20 Future me who will look into this error: A null check for `this` in that area of the code, might just do the trick.

**Comment by lilyremigia** [comment]
@Yanstory  Can you test if the new [pre-release](https://github.com/Tudi20/Universal-THCRAP-Launcher/releases/tag/1.0.0-pre1) fixes the issue?

**Comment by Yanstory** [comment]
Doesn't work with same error.

**Comment by lilyremigia** [comment]
@Yanstory By chance does [pre3](https://github.com/Tudi20/Universal-THCRAP-Launcher/releases/tag/1.0.0-pre3) fix this?

**Comment by Yanstory** [comment]
No, with same error.
However, if **remove** this action binding
![image](https://user-images.githubusercontent.com/5153875/58444090-063fd680-8129-11e9-8d09-e13a1fc68f31.png)
The app can run normally (don't know if there's any other bug, but seems it works).

**Comment by lilyremigia** [comment]
Plan B from me: Put the whole fucking thing in a try-catch block and frick it.

**Comment by lilyremigia** [comment]
Does [1.0.0](https://github.com/Tudi20/Universal-THCRAP-Launcher/releases/tag/1.0.0) fix it?

**Comment by Yanstory** [comment]
Yes, it fixed. Works well just now. 🎉

**Comment by lilyremigia** [comment]
Great!
