### ISSUE TITLE
[Feature] Support .thcrap files

### ISSUE THREAD

**Issue by brliron** [Tudi20/Universal-THCRAP-Launcher#13]
There is a plan to replace .js with .thcrap for patch stacks one day. When it happens, your launcher should support .thcrap files as well.

**Comment by lilyremigia** [comment]
@brliron  Should be done 22727d25d4bcc2eda3cbb0efceec060dbaa093aa
Please reopen if .thcrap support is implemented before and it's broken, before I have done ReUTL.
