### ISSUE TITLE
[Feature] Jump list support

### ISSUE THREAD

**Issue by brliron** [Tudi20/Universal-THCRAP-Launcher#15]
It would be nice if this launcher could support jump lists - pin the launcher in the Windows task bar, right-click on it, and you can run your last games with your last patches without even running the launcher!
It would also be nice to be able to pin a game+config in the jump list, but I have no idea how the UI for that would be.

Also, I think it's possible to share the content of the jump list with thcrap_launcher. Thcrap_launcher doesn't support the jump list for now, but that's something we should think about.

**Comment by lilyremigia** [comment]
Should be done 7dcd844bb406760efa47a615417b13c1b08c4773
