### ISSUE TITLE
[FEATURE] Provide friendly, translated names for game targets

### ISSUE THREAD

**Issue by WindowDump** [Tudi20/Universal-THCRAP-Launcher#16]
**Is your feature request related to a problem? Please describe.**
The list of targets to launch is the same as the keys in thcrap's games.js, listed in the format of "thxx" or "thxx_custom". This can be unclear for users not intimately familiar with the naming convention for the games.

**Describe the solution you'd like**
Provide the option to replace the game numbers with a friendly, translated name for the games, i.e. replacing "th06" with "Touhou Koumakyou ~ the Embodiment of Scarlet Devil", replacing "th07" with "Touhou Youyoumu ~ Perfect Cherry Blossom", etc. Ideally this should also support each localization. If a translation of a certain target isn't known, simply provide the target's name, like the current behavior. The current system should still be offered for those that prefer it.

**Describe alternatives you've considered**
I have personally had success by memorizing every game's number and English title, so it is easy for me to find which game I want to launch.

**Additional context**
A possible solution might involve parsing patch files in the thcrap directories for the names of the games; but given that the translations of the games don't change very often and a new game is released at most once every 6 months, this would probably be overkill.

**Comment by lilyremigia** [comment]
Done 4f829b13167df27c4997ad5b401da65b5ec28c26
