### ISSUE TITLE
[BUG] UTL 1.1.0 pre3 stuck after closing thcrap

### ISSUE THREAD

**Issue by AsyrafFile** [Tudi20/Universal-THCRAP-Launcher#40]
UTL stuck and cannot responding after closing thcrap when "Only allow one executable" ticked. Even thcrap_loader.exe fully closed on both normal and kill via. Task Manager.

**Comment by lilyremigia** [comment]
Done 2577d9bb10777987830b3bb48d6b7cae67184b08
