### ISSUE TITLE
Add more title combinations

### ISSUE THREAD

**Issue by IgoSplashman** [Tudi20/Universal-THCRAP-Launcher#42]
![2019-07-06 01_24_32-thcrap_brliron](https://user-images.githubusercontent.com/7331514/60748318-e18f1800-9f8c-11e9-9d42-7f61c88061ce.png)

Changing between game numbers, initials, short and long names is fine and well, but it would be cool if you could make the list show the game numbers AND the titles, as in "thxx: Touhou Kablub ~ Blub of Blubbing". This would be very useful for ordering the games chronologically. 

Perhaps you could remove "thxx" from the dropdown list and add it as a separate checkmark feature in the UTL settings, for example _Show the game number "thxx: " in front of the game title?_.

Also, "Short name" and "Long name" sounds a bit vague. How about "English subtitle" and "JP main title and EN subtitle"

**Comment by lilyremigia** [comment]
Done https://github.com/Tudi20/Universal-THCRAP-Launcher/compare/b82636b2daecd7ed95e807f27c61d17efba55d3d...master
