### ISSUE TITLE
[BUG] Configuration with white-space in name can't start

### ISSUE THREAD

**Issue by Dobby233Liu** [Tudi20/Universal-THCRAP-Launcher#55]
**Describe the bug**
As described in the title: Configuration with white-space in it's name can't start.

**To Reproduce**
1. Create a configuration using `thcrap_configure.exe`
2. But when the configure tool tell you give a name to the configuration, name it something like `it's a bug`
3. Complete configuration, then open UTL.
4. Try to start any game in the THCRAP configuration, but this time THCRAP will prompt something like `bug.js can't be found in <dir>`

**Expected behavior**
THCRAP will correctly start.

**Screenshots**
![2019-08-17 121541](https://user-images.githubusercontent.com/28653235/63206557-5fe0ed00-c0e9-11e9-8d30-2f00663e8147.png) (this configration can't start)
![2019-08-17 121610](https://user-images.githubusercontent.com/28653235/63206565-7b4bf800-c0e9-11e9-8c31-b7dccb869537.png)
(this one doesn't have space in it's name, it can start)

**Desktop**
 - OS: Windows 10
 - Version: UTL 1.1.0-pre10

**Comment by Dobby233Liu** [comment]
a little point is:
![批注 2019-08-17 123257](https://user-images.githubusercontent.com/28653235/63206645-32953e80-c0eb-11e9-8062-44adf105c6a5.png)
(thcrap quoted the configuration script name in the shortcut they generate)
![批注 2019-08-17 123509](https://user-images.githubusercontent.com/28653235/63206661-7b4cf780-c0eb-11e9-8c41-543c6e1aa38e.png)
(and it can run)

**Comment by lilyremigia** [comment]
I think, I already fixed that, just didn't release it? 4573363c53c381944645ce7dd40f971702ce12ac

**Comment by Dobby233Liu** [comment]
yes i think

**Comment by lilyremigia** [comment]
https://github.com/Tudi20/Universal-THCRAP-Launcher/releases/tag/1.1.0-rumia
