### ISSUE TITLE
Enable patches stacking

### ISSUE THREAD

**Issue by MagicalDrizzle** [Tudi20/Universal-THCRAP-Launcher#58]
As of now, the only way to use more than two patches at once is to run the configure then create a new js file, which is quite tiring if you have lots of patches. A possible solution is to enable choosing more than two patches in the dialog. You only have to run the configure once for each patch, and then combine them all you like.
Example: Root folder has en.js, vi.js, RNG.js, alphes.js.
Then you can run en-vi, en-RNG, vi-RNG, vi- alphes,...

**Comment by lilyremigia** [comment]
1. No major feature will be added to this version of utl
2. There's no custom ordering in the list, and as such telling the way the patches should be stacked would be too complicated.
3. I'm lazy.
