### ISSUE TITLE
[BUG] "Hide extension on patch list" hides extension from thcrap_loader

### ISSUE THREAD

**Issue by WindowDump** [Tudi20/Universal-THCRAP-Launcher#59]
**Describe the bug**
If the "Hide extension on patch list" option in Settings is ticked, the hidden extension also applies to the arguments passed to thcrap. This result in thcrap giving the error "No run configuration .js file given" and closing before launching the target game.

**To Reproduce**
1. In settings, enable "Hide extension on patch list"
2. Choose any non-vanilla patch and any game.
3. Click "Start Game"
4. thcrap will display an error dialog.

**Expected behavior**
thcrap launches the game successfully, as when the "Hide extension on patch list" option is disabled.

**Screenshots**
n/a (but I posted some on Discord)

**Desktop (please complete the following information):**
 - OS: Windows 10 v. 1903
 - Version 1.1.0

**Additional context**
This is visible in the log - you'll see a line like ``Starting thcrap with "en" th17`` instead of ``Starting thcrap with "en.js" th17``.

You can manually create the same error dialog from thcrap by opening a shell and running (for example) ``thcrap_loader.exe "en" th17``

**Comment by lilyremigia** [comment]
Fixed https://github.com/Tudi20/Universal-THCRAP-Launcher/releases/tag/1.1.0a
