### ISSUE TITLE
[BUG] Language fallback to English

### ISSUE THREAD

**Issue by AsyrafFile** [Tudi20/Universal-THCRAP-Launcher#62]
Language setting back to English when I restarted the program.

[utl-log.txt](https://github.com/Tudi20/Universal-THCRAP-Launcher/files/3627977/utl-log.txt)

**Comment by lilyremigia** [comment]
Nothing seems to indicate that the language was changed while loading. But
I will do some testing, myself with languages.

Zulhilmi Asyraf <notifications@github.com> ezt írta (időpont: 2019. szept.
18., Sze 21:14):

**Comment by lilyremigia** [comment]
https://github.com/Tudi20/Universal-THCRAP-Launcher/releases/tag/1.1.0b
