### ISSUE TITLE
[BUG] Launcher is not being created

### ISSUE THREAD

**Issue by CodedRubyChan** [Tudi20/Universal-THCRAP-Launcher#80]
**Describe the bug**
If i download the Launcher, put it in the "bin" folder and run the universal launcher i get some Error. (Translated from German) it some MessageBox has invalid Arguments error or something

**To Reproduce**
1. Download the newest Release
2. extract the .exe and .dll to the "bin" folder which is next to the thcrap.exe and thcrap_loader.exe
3. run the universal launcher
4. Error.

**Expected behavior**
A new Universal Launcher should be created with some folders next to the thcrap.exe

**Screenshots**
![image](https://user-images.githubusercontent.com/40892993/188411531-e49b19b2-cd95-47e8-ab9f-1dc7551d4532.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Comment by Noonerboi21** [comment]
I'm also having the same problem as well

**Comment by CodedRubyChan** [comment]
nvm, i had to start the normal launcher atleast one time
